import { renderMarkdown } from '@/lib/renderMarkdown';

const IMAGE_TAG_RE = /\[IMAGE:((?:https?:\/\/|data:)[^\]]+)\]/g;
const VIDEO_TAG_RE = /\[VIDEO:((?:https?:\/\/|data:)[^\]]+)\]/g;

/**
 * Renders ROKCAT message text with inline images and videos.
 * Detects [IMAGE:url] and [VIDEO:url] tags and replaces them with media elements.
 */
export default function RokCatMediaRenderer({ text }: { text: string }) {
  // Check if text contains media tags
  const hasMedia = IMAGE_TAG_RE.test(text) || VIDEO_TAG_RE.test(text);
  // Reset regex lastIndex
  IMAGE_TAG_RE.lastIndex = 0;
  VIDEO_TAG_RE.lastIndex = 0;

  if (!hasMedia) {
    return <>{renderMarkdown(text)}</>;
  }

  // Split text into segments: regular text and media tags
  const segments: Array<{ type: 'text' | 'image' | 'video'; content: string }> = [];
  const combinedRe = /\[(IMAGE|VIDEO):(https?:\/\/[^\]]+)\]/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = combinedRe.exec(text)) !== null) {
    if (match.index > lastIndex) {
      segments.push({ type: 'text', content: text.slice(lastIndex, match.index) });
    }
    segments.push({
      type: match[1].toLowerCase() as 'image' | 'video',
      content: match[2],
    });
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < text.length) {
    segments.push({ type: 'text', content: text.slice(lastIndex) });
  }

  return (
    <>
      {segments.map((seg, i) => {
        if (seg.type === 'image') {
          return (
            <div key={i} className="my-1.5">
              <a href={seg.content} target="_blank" rel="noopener noreferrer">
                <img
                  src={seg.content}
                  alt="Generated by Grok Imagine"
                  className="max-w-full max-h-48 rounded border border-[#00e5ff]/20 hover:border-[#00e5ff]/50 transition-colors cursor-pointer"
                  loading="lazy"
                />
              </a>
            </div>
          );
        }
        if (seg.type === 'video') {
          return (
            <div key={i} className="my-1.5">
              <video
                src={seg.content}
                controls
                className="max-w-full max-h-48 rounded border border-[#00e5ff]/20"
                preload="metadata"
              />
            </div>
          );
        }
        return <span key={i}>{renderMarkdown(seg.content)}</span>;
      })}
    </>
  );
}
